spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/unidad1Spring
spring.datasource.username=postgres
spring.datasource.password=a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html